### ISSUE TITLE
Evaluation Center and MobSOS Surveys integration

### ISSUE THREAD

**Issue by Navidda** [rwth-acis/mobsos#7]
Currently, the results of the survey can only be seen on the mobsos surveys frontend. As we are planning to provide a single frontend for the mobsos services, (the [Evaluation Center](https://github.com/rwth-acis/mobsos-evaluation-center), it should at least provide visualizations of results of a survey.
Users should be able to simply link a survey to the success model of an application.
The results should be presented alongside the success dimensions of the success model.

**Comment by lakhoune** [comment]
we should also check that all visualization types can actually be presented in the evaluation center and if some are missing, create an issue for them in the evaluation center

**Comment by lakhoune** [comment]
introduced in https://github.com/rwth-acis/mobsos-query-visualization/pull/22
